version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/breakfast_advisor
hooks:
  BeforeInstall:
    - location: scripts/install_pip
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root